In [1]:
import pandas as pd
from pathlib import Path

In [2]:
input_file = Path.cwd()/'course_history.csv'

In [3]:
df = pd.read_csv(input_file)

In [4]:
df

,Name,Code,Facilitator,Session,Time,Weeks,Run Time,Min Quota,Quota,Students,Members,Non-members,Waiting,Operating Cost
0,Bonsai for Beginners,GD3,Alicia Zablah,18-Aug-2021,2:00pm,4,8:00,4.0,4,0,0,0,0,$240.00
1,Bonsai for Beginners,GD3,Alicia Zablah,22-Sep-2021,3:00pm,1,8:00,4.0,4,0,0,0,0,$240.00
2,Book Club,CA1,Diane Bailey,27-Aug-2021,9:30am,2,0:45,0.0,15,6,6,0,0,$0.00
3,Botanical Ink Drawing - Beginners,AC62,Tania Daymond,27-Jul-2021,12:45pm,8,16:00,6.0,9,3,3,0,0,$800.00
4,Botanical Ink Drawing - Ongoing,AC56,Tania Daymond,26-Jul-2021,9:30am,8,16:00,6.0,12,5,5,0,0,$800.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,Tai Chi for Health and Stability,HW4,Maurice Werder,27-Jul-2021,8:00am,9,9:00,4.0,8,0,0,0,0,$270.00
67,Tai Chi for Health and Stability,HW4,Maurice Werder,27-Jul-2021,4:45pm,9,9:00,4.0,8,0,0,0,0,$270.00
68,Watercolours Beginners and Ongoing,AC13,Verena Marmion,26-Jul-2021,12:00pm,8,16:00,5.0,10,4,4,0,0,$560.00
69,Yoga for Everybody HW14,HW14,Andi Bach,26-Jul-2021,5:00pm,8,8:00,5.0,6,0,0,0,0,$400.00
70,NaN,NaN,NaN,NaN,459,939:45,733,NaN,204,186,18,3,"$32,111.00",NaN

In [5]:
df.columns

Index(['Name', 'Code', 'Facilitator', 'Session', 'Time', 'Weeks', 'Run Time',
       'Min Quota', 'Quota', 'Students', 'Members', 'Non-members', 'Waiting',
       'Operating Cost'],
      dtype='object')

In [6]:
df.drop(['Facilitator', 'Session', 'Time', 'Weeks', 'Run Time',
       'Min Quota', 'Quota', 'Students', 'Members', 'Non-members', 'Waiting',
       'Operating Cost'], axis=1, inplace=True)

In [7]:
df

                                  Name  Code
0                 Bonsai for Beginners   GD3
1                 Bonsai for Beginners   GD3
2                           Book Club    CA1
3    Botanical Ink Drawing - Beginners  AC62
4      Botanical Ink Drawing - Ongoing  AC56
..                                 ...   ...
66    Tai Chi for Health and Stability   HW4
67    Tai Chi for Health and Stability   HW4
68  Watercolours Beginners and Ongoing  AC13
69             Yoga for Everybody HW14  HW14
70                                 NaN   NaN

[71 rows x 2 columns]

In [8]:
df.to_csv('hurrah.tab',index=False, sep='\t')

In [9]:
html = df.to_html(index=False)
text_file = open("index.html", "w")
text_file.write(html)
text_file.close()